name: Backend Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Backend tests
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: cd backend
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
